Comma separated -w flags
ffuf/ffuf pull request #294
Opened 2020-09-13 00:40 UTC by averagesecurityguy

This is to resolve https://github.com/ffuf/ffuf/issues/290. The request was for input like `-w file1.txt:W1, file2.txt:W2` unfortunately, that won't work because the `flag` module splits the input on whitespace so main.go never sees the rest of the comma delimited list. If you remove the space and instead use `-w file1.txt:W1,file2.txt:W2`, this code change will properly parse that.

```
% ./ffuf -u https://W2.io/W1 -w ./wordlist.txt:W1,./domains.txt:W2

        /'___\  /'___\           /'___\       
       /\ \__/ /\ \__/  __  __  /\ \__/       
       \ \ ,__\\ \ ,__\/\ \/\ \ \ \ ,__\      
        \ \ \_/ \ \ \_/\ \ \_\ \ \ \ \_/      
         \ \_\   \ \_\  \ \____/  \ \_\       
          \/_/    \/_/   \/___/    \/_/       

       v1.2.0-git
________________________________________________

 :: Method           : GET
 :: URL              : https://W2.io/W1
 :: Wordlist         : W1: ./wordlist.txt
 :: Wordlist         : W2: ./domains.txt
 :: Follow redirects : false
 :: Calibration      : false
 :: Timeout          : 10
 :: Threads          : 40
 :: Matcher          : Response status: 200,204,301,302,307,401,403
________________________________________________

:: Progress: [1/1] :: Job [1/1] :: 0 req/sec :: Duration: [0:00:00] :: Errors: 0[Status: 301, Size: 162, Words: 5, Lines: 8]
    * W1: admin
    * W2: codingo

:: Progress: [1/1] :: Job [1/1] :: 0 req/sec :: Duration: [0:00:00] :: Errors: 0:: Progress: [1/1] :: Job [1/1] :: 0 req/sec :: Duration: [0:00:00] :: Errors: 0 ::

```

2020-09-13 13:55 UTC, joohoi requested changes
Thanks for the PR! The code looks good, but if you could add an entry to CHANGELOG.md as well as your own name to CONTRIBUTORS.md, it would be great!

2020-09-14 11:22 UTC, joohoi commented
Just one more thing; I would love the CHANGELOG.md to be in alphabetic order

2020-09-14 14:14 UTC, averagesecurityguy commented
I assumed you meant CONTRIBUTORS.md and not CHANGELOG.md. Please let me know if that was a misunderstanding on my part.

2020-09-14 20:13 UTC, joohoi approved these changes
You are right, I mistyped in hurry. LGTM, merging!

2020-09-14 20:13 UTC, merged