Fix -of all output (#451)
ffuf/ffuf pull request #462
Opened 2021-06-14 20:10 UTC by Hazegard

# Description

This PR intends to fix an issue introduced by the commit f97c2f7600b0f9fd2acd5e970a13a357ca310a26.
When using the `-of all` option, only one file is create (each format overrides the same file in fact)

Fixes: #451

## Additonally

- [x] If this is the first time you are contributing to ffuf, add your name to `CONTRIBUTORS.md`. 
The file should be alphabetically ordered.
- [x] Add a short description of the fix to `CHANGELOG.md`

Thanks for contributing to ffuf :)

2021-07-26 00:44 UTC, bsysop commented
Good fix @Hazegard

2022-01-22 18:02 UTC, joohoi requested changes
Sorry that it took so long to get around to reviewing this PR. It looks good, and looks like you added HTTP/2 support in this PR too! Could you resolve the merge conflict in CHANGELOG.md while adding a line about the HTTP/2 feature addition? Other than that this PR seems ready to merge.

2022-01-22 18:43 UTC, Hazegard commented
Hi!

Thanks for reviewing the PR.
I resolved the merge conflict in CHANGELOG.md, and added a line about the HTTP2 support.

2022-01-28 15:49 UTC, joohoi approved these changes
All good, thanks for the PR!

2022-01-28 15:49 UTC, merged