Added additional proxy URL verification
ffuf/ffuf pull request #574
Opened 2022-07-29 06:51 UTC by denandz

# Description

This pull request adds additional checking for proxy and replay-proxy parameters, as well as adding some tests to make sure the parser is working how it's expected to.  Go's `url.parse` alone does not provide enough verification to determine whether a given URL matches the requirements for a proxy passed to a HTTP transport.

Fixes: #573

2023-02-02 14:21 UTC, joohoi requested changes
LGTM with this proposed small nit

2023-02-02 14:21 UTC, joohoi commented on pkg/ffuf/optionsparser.go
> +		if err != nil || u.Opaque != "" || (u.Scheme != "http" && u.Scheme != "https" && u.Scheme != "socks5") {
```suggestion
		if err != nil || u.Opaque != "" || (u.Scheme != "http" && u.Scheme != "https" && u.Scheme != "socks5" && u.Scheme != "socks5h") {
```
Even though they're [handled similarly by the Go net/proxy](https://cs.opensource.google/go/x/net/+/refs/tags/v0.5.0:proxy/proxy.go;l=92-99), there is an additional valid flavor of `socks5` called `socks5h`, so in the spirit of completeness, I think we should allow that too.

2023-02-02 14:21 UTC, joohoi commented on pkg/ffuf/optionsparser.go
> +		if err != nil || u.Opaque != "" || (u.Scheme != "http" && u.Scheme != "https" && u.Scheme != "socks5") {
```suggestion
		if err != nil || u.Opaque != "" || (u.Scheme != "http" && u.Scheme != "https" && u.Scheme != "socks5" && u.Scheme != "socks5h") {
```
Even though they're [handled similarly by the Go net/proxy](https://cs.opensource.google/go/x/net/+/refs/tags/v0.5.0:proxy/proxy.go;l=92-99), there is an additional valid flavor of `socks5` called `socks5h`, so in the spirit of completeness, I think we should allow that too.

2023-02-02 19:02 UTC, denandz commented
> LGTM with this proposed small nit

good catch! Committed.

2023-02-03 07:09 UTC, joohoi approved these changes
Thanks for the quick fix!

2023-02-03 07:09 UTC, merged