[Fix] Fixed multiline output when using only one fuzz variable (issue #645)
ffuf/ffuf pull request #656
Opened 2023-03-03 18:59 UTC by p0dalirius

# Description

Fixed multi-line output when using only one fuzz variable (issue #645)

Fixes: #645

---

## Bug source

In version 2.0 of fuff, `FFUFHASH` was added. 

https://github.com/ffuf/ffuf/blob/b2c1f9471f5bc275912c9c8194e88593d2636597/CHANGELOG.md?plain=1#L8

This variable is set in the `Input` map of the result structure:

https://github.com/ffuf/ffuf/blob/b2c1f9471f5bc275912c9c8194e88593d2636597/main.go#L397

This triggers two bugs

### Bug 1

Because of this, the size of `res.Input` is now at least 2. Therefore all output modes will be multi-lines since the condition `len(res.Input) > 1` is never met in the function [`PrintResult()`](https://github.com/p0dalirius/ffuf/blob/master/pkg/output/stdout.go#L369) in `pkg/output/stdout.go`.

https://github.com/p0dalirius/ffuf/blob/b2c1f9471f5bc275912c9c8194e88593d2636597/pkg/output/stdout.go#L375-L377

Changing the condition `len(res.Input) > 1` to `len(s.fuzzkeywords) > 1` fixes this bug.

### Bug 2

Another bug then occurs when only one fuzz variable is passed and results are printed. When `prepareInputsOneLine()` in `pkg/output/stdout.go` gets called, the function iterates on res.Input, therefore printing `FFUFHASH` too.

https://github.com/p0dalirius/ffuf/blob/master/pkg/output/stdout.go#L386

https://github.com/p0dalirius/ffuf/blob/master/pkg/output/stdout.go#L395

Changing the iteration on `res.Input` to an iteration on `s.fuzzkeywords` fixes this bug.

---

## New behavior

When fuzzing only one variable:

![image](https://user-images.githubusercontent.com/79218792/222801343-7a9d2ed3-3d0e-4204-a29c-bf40b35c15af.png)

When fuzzing two and more variables:

![image](https://user-images.githubusercontent.com/79218792/222801153-94f0e468-ae1a-430b-93ee-33db2a11c563.png)

Best regards,

2023-03-29 11:40 UTC, p0dalirius commented
Hey @joohoi

Can you take a look at this? Everything is fixed in this PR, and the current bug (https://github.com/ffuf/ffuf/issues/645) is really annoying.

Best regards,

2023-04-21 14:19 UTC, joohoi requested changes
Thanks for the fix. Besides the one comment this LGTM.

2023-04-21 14:19 UTC, joohoi commented on pkg/output/stdout.go
>  	if len(res.Input) > 1 {
```suggestion
	if len(s.fuzzkeywords) > 1 {
```

2023-04-21 14:19 UTC, joohoi commented on pkg/output/stdout.go
>  	if len(res.Input) > 1 {
This needs to be changed to observe the fuzzkeywords variable as well.

2023-04-21 14:21 UTC, joohoi approved these changes
Commited the suggestion, so this is ready to merge.

2023-04-21 14:22 UTC, merged

2023-06-12 16:43 UTC, sk0x1234 commented
using the latest git build

silent/quit ` -s` option  producing in wrong format
FUZZ anf FFUFHASH interchanged. im using latest git build

![image](https://github.com/ffuf/ffuf/assets/18193527/e66606a2-4347-4736-b3b7-fbb86d5d8e4d)

![image](https://github.com/ffuf/ffuf/assets/18193527/6db48801-c6ba-47e7-bfa0-8cbbcac58327)

2023-07-27 01:28 UTC, felipecaon commented
Seems like this issue is back, using `v2.0.0`